"""Centralized environment / runtime configuration for VisePanda v7.

Every secret defaults to an empty string so the app boots cleanly with no env
vars. Feature endpoints branch on has_*() helpers and degrade gracefully.
"""
from __future__ import annotations

import os
import secrets
from pathlib import Path

VERSION = "7.0.0"
APP_NAME = "VisePanda"

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data"
TRANSLATIONS_DIR = DATA_DIR / "translations"
WEB_DIR = ROOT_DIR / "web"
LOCAL_DB_PATH = DATA_DIR / "auth.db.json"


def _env(name: str, default: str = "") -> str:
    value = os.environ.get(name)
    return value.strip() if value not in (None, "") else default


# ---------- App ----------
APP_BASE_URL = _env("APP_BASE_URL", "https://claude.go2china.space").rstrip("/")
APP_ENV = _env("APP_ENV", "development").lower()

# ---------- AI: DeepSeek (chat + translate) ----------
DEEPSEEK_API_KEY = _env("DEEPSEEK_API_KEY")
DEEPSEEK_BASE_URL = _env("DEEPSEEK_BASE_URL", "https://api.deepseek.com").rstrip("/")
DEEPSEEK_MODEL = _env("DEEPSEEK_MODEL", "deepseek-chat")

# ---------- Voice: Alibaba DashScope (Qwen3-TTS, Qwen3-ASR) ----------
DASHSCOPE_API_KEY = _env("DASHSCOPE_API_KEY")
DASHSCOPE_BASE_URL = _env("DASHSCOPE_BASE_URL", "https://dashscope.aliyuncs.com").rstrip("/")
QWEN_TTS_MODEL = _env("QWEN_TTS_MODEL", "qwen3-tts-flash")
QWEN_TTS_VOICE = _env("QWEN_TTS_VOICE", "Chelsie")
QWEN_ASR_MODEL = _env("QWEN_ASR_MODEL", "qwen3-asr-flash")

# ---------- Storage: Supabase REST ----------
SUPABASE_URL = _env("SUPABASE_URL").rstrip("/")
SUPABASE_ANON_KEY = _env("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_KEY = _env("SUPABASE_SERVICE_KEY")

# ---------- Email: Resend ----------
RESEND_API_KEY = _env("RESEND_API_KEY")
RESEND_FROM = _env("RESEND_FROM", "VisePanda <hello@go2china.space>")

# ---------- Google OAuth ----------
GOOGLE_CLIENT_ID = _env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = _env("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = _env(
    "GOOGLE_REDIRECT_URI", f"{APP_BASE_URL}/api/auth/callback"
)

# ---------- JWT / Session ----------
_jwt_env = _env("JWT_SECRET")
if _jwt_env:
    JWT_SECRET = _jwt_env
    JWT_SECRET_AUTOGENERATED = False
else:
    JWT_SECRET = secrets.token_hex(32)
    JWT_SECRET_AUTOGENERATED = True
JWT_TTL_DAYS = int(_env("JWT_TTL_DAYS", "7"))
SESSION_COOKIE = "vp_session"


# ---------- Feature flags ----------

def has_deepseek() -> bool:
    return bool(DEEPSEEK_API_KEY)


def has_voice() -> bool:
    return bool(DASHSCOPE_API_KEY)


def has_supabase() -> bool:
    return bool(SUPABASE_URL and SUPABASE_SERVICE_KEY)


def has_email() -> bool:
    return bool(RESEND_API_KEY)


def has_google() -> bool:
    return bool(GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET)


def is_production() -> bool:
    return APP_ENV == "production"


def public_features() -> dict:
    """Booleans exposed to the frontend at /api/config/public."""
    return {
        "version": VERSION,
        "has_deepseek": has_deepseek(),
        "has_voice": has_voice(),
        "has_supabase": has_supabase(),
        "has_email": has_email(),
        "has_google": has_google(),
        "app_env": APP_ENV,
    }
